name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "example/**"
      - "Project.toml"
      - "Manifest.toml"
      - "**/*.jl"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "test/**"
      - "example/**"
      - "Project.toml"
      - "Manifest.toml"
      - "**/*.jl"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        julia-version: ['1.10', '1.11', '1.12']
    steps:
      - uses: actions/checkout@v4

      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix['julia-version'] }}

      - name: Instantiate and run tests
        env:
          JULIA_NUM_THREADS: 2
          JULIA_PKG_PRECOMPILE_AUTO: "0"
        run: |
          julia --color=yes -e '
            using Pkg;
            Pkg.activate(pwd());
            Pkg.instantiate(; allow_autoprecomp=false);
            using Cross;
            Pkg.test();
          '
